# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_authenticate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('hobby_name', models.CharField(max_length=128)),
                ('interest_level', models.IntegerField()),
            ],
        ),
    ]
