# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
